### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Aljullu** [Aljullu/react-lazy-load-image-component#1]
Some ideas that might or might not be implemented in the future, but good to have in a list.

* [x] Add a prop to load the image by default. (1aa87daba46b1a918976d56c441c5aa1b93d43bd)
* [ ] Create a generic component to lazy load anything, not only images.
* [ ] Experiment with components that listen to scroll/resize events without needing the HOC.
* [ ] Add some way to have a low-quality image placeholder that doesn't dissapear when loading the image. Probably adding a wrapper element with `background-image`.
* [ ] Make it work with `overflow: scroll` containers.

**Comment by angelcustodio** [comment]
Is the project still alive? @Aljullu

**Comment by Aljullu** [comment]
Yes, it is. But my time is limited! :slightly_smiling_face: 

Since the first version of the package was released, I have been publishing [minor updates with fixes](https://github.com/Aljullu/react-lazy-load-image-component/releases) every time somebody reported a bug.

But the 'big features' from these roadmap usually take more time and I can't promise any release date. I have been experimenting with IntersectionObserver in a branch (#6), but there is still work to do.

Contributions are accepted and appreciated, tho! :wink:

**Comment by BramDecuypere** [comment]
@Aljullu Great work! I was just wondering if not lazy-loading when the image has already been requested was somehow supported? Because now when I move to a page and come back, the page scroll is not correct because the images at the top are not loaded.

Or should this be fixed with placeholders? But what if you never know how big the size is of the image because of responsiveness?

Wish you all the best in these times!
